name: First workflow

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Runs a sample github actions
        run: echo "This workflow runs successfully for this particular action"
      - name: Simulating error
        run: echo "Error taking place"
